repos:
  - repo: local
    hooks:
      - id: commit-msg-lint
        name: commit message lint
        entry: python scripts/validate_commit_msg.py
        language: system
        stages: [commit-msg]
