apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpconfigs.mcp.mycompany.com
spec:
  group: mcp.mycompany.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: object
                  additionalProperties:
                    type: string
                methods:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: mcpconfigs
    singular: mcpconfig
    kind: MCPConfig
    shortNames:
      - mcpconf
