apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["mcp.mycompany.com"]
    resources: ["mcpconfigs"]
    verbs: ["get", "list", "watch"]
