name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e .[dev]
      - run: python -m py_compile sidecar/main.py mcp_operator/mcp_operator.py
      - run: pytest --cov=sidecar --cov=mcp_operator --cov-report=term --cov-fail-under=80
      - name: Build sidecar image
        run: docker build -t mcp-sidecar:latest ./sidecar
      - name: Save image
        run: docker save mcp-sidecar:latest -o mcp-sidecar.tar
      - name: Install helm
        run: |
          sudo apt-get update
          sudo apt-get install -y helm
      - name: Package chart
        run: helm package charts/mcp-operator
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            mcp-sidecar.tar
            mcp-operator-*.tgz

  release:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          name: v0.1.0
          body: |
            Initial release providing:
            - FastAPI sidecar exposing microservice APIs
            - Kopf operator that registers MCP services
            - Helm chart for deployment
          files: |
            mcp-sidecar.tar
            mcp-operator-*.tgz
